package ui

import (
	"context"
	"errors"
	"fmt"
	"strings"

	tea "charm.land/bubbletea/v2"
	gitbackend "github.com/richard/lazymagit/internal/git"
	"github.com/richard/lazymagit/internal/keymap"
)

const branchPrefix = "b"

// Branch command IDs are generated by the registry. Registration is keyed by
// the exact upstream command instead of duplicating those generated strings.
func init() {
	branchOptions := []string{"transient:magit-branch:--recurse-submodules"}
	RegisterWorkflowCapabilities(capabilitiesForTransient("magit-branch", map[string][]string{
		"magit-checkout":            branchOptions,
		"magit-checkout-remote-ref": branchOptions,
		"magit-branch-checkout":     branchOptions,
	})...)
	RegisterWorkflowDomain(func(m *Model) map[keymap.CommandID]WorkflowHandler {
		handlers := map[string]WorkflowHandler{
			"magit-checkout":              branchCheckoutRevision,
			"magit-checkout-remote-ref":   branchCheckoutRemote,
			"magit-update-default-branch": remoteDefaultBranchWorkflow,
			"magit-branch-checkout":       branchCheckoutLocal,
			"magit-branch-orphan":         branchOrphan,
			"magit-branch-and-checkout":   branchCreateAndCheckout,
			"magit-worktree-checkout":     branchWorktreeExisting,
			"magit-branch-create":         branchCreateOnly,
			"magit-worktree-branch":       branchWorktreeNew,
			"magit-branch-configure":      branchConfigure,
			"magit-branch-rename":         branchRename,
			"magit-branch-reset":          branchReset,
			"magit-branch-delete":         branchDelete,
		}
		registered := make(map[keymap.CommandID]WorkflowHandler, len(handlers))
		checkoutHandlers := map[string]bool{"magit-checkout": true, "magit-checkout-remote-ref": true, "magit-branch-checkout": true}
		var recurseOption keymap.CommandID
		for _, binding := range keymap.Registry() {
			if binding.Scheme != keymap.SchemeMagit || binding.Context != keymap.ContextTransient+branchPrefix {
				continue
			}
			if binding.UpstreamCommand == "transient:magit-branch:--recurse-submodules" {
				recurseOption = binding.Command
			}
			if handler := handlers[binding.UpstreamCommand]; handler != nil {
				upstream, checkout := binding.UpstreamCommand, checkoutHandlers[binding.UpstreamCommand]
				registered[binding.Command] = func(m *Model, command WorkflowCommand) tea.Cmd {
					if (command.Options[recurseOption].Enabled || command.Options[recurseOption].Value != "") && !checkout {
						m.setError(fmt.Errorf("%s does not consume recursive-submodule checkout", upstream))
						return nil
					}
					return handler(m, command)
				}
			}
		}
		return registered
	})
}

func requireBranchRepository(m *Model) error {
	if m.repo == nil {
		return errors.New("branch workflow requires a repository")
	}
	return nil
}

func loadBranchWorkflow(m *Model, name string, loader WorkflowLoader) tea.Cmd {
	if err := requireBranchRepository(m); err != nil {
		m.setError(err)
		return nil
	}
	return m.LoadWorkflow(name, loader)
}

func branchChoices(ctx context.Context, repo *gitbackend.Repository, includeRemote, includeCurrent bool) ([]WorkflowChoice, string, error) {
	branches, err := repo.Branches(ctx)
	if err != nil {
		return nil, "", err
	}
	var choices []WorkflowChoice
	current := ""
	for _, branch := range branches {
		if branch.Current {
			current = branch.Name
		}
		if branch.Remote && !includeRemote || branch.Current && !includeCurrent {
			continue
		}
		label := branch.Name
		if branch.Current {
			label += " (current)"
		}
		if branch.Remote {
			label += " (remote-tracking)"
		}
		choices = append(choices, WorkflowChoice{Value: branch.Name, Label: label})
	}
	return choices, current, nil
}

func requireChoices(choices []WorkflowChoice, what string) error {
	if len(choices) == 0 {
		return fmt.Errorf("no %s available", what)
	}
	return nil
}

func choiceDefault(choices []WorkflowChoice, preferred string) string {
	for _, choice := range choices {
		if choice.Value == preferred {
			return preferred
		}
	}
	if len(choices) > 0 {
		return choices[0].Value
	}
	return ""
}

func branchCheckoutRevision(m *Model, command WorkflowCommand) tea.Cmd {
	return loadBranchWorkflow(m, "branch/revision choices", func(ctx context.Context) (WorkflowDialog, error) {
		choices, current, err := branchChoices(ctx, m.repo, true, true)
		if err != nil {
			return WorkflowDialog{}, err
		}
		if current == "" {
			current = "HEAD"
		}
		choice := 0
		for i := range choices {
			if choices[i].Value == current {
				choice = i
				break
			}
		}
		return WorkflowDialog{
			Title: "Checkout branch or revision", Operation: "checkout branch/revision", ActionLabel: "Checkout",
			Plan:   []string{"Type to filter local and remote-tracking branches", "A custom revision is checked out with detached HEAD"},
			Fields: []WorkflowField{{Name: "revision", Label: "Search", Kind: WorkflowSearch, Value: current, Choices: choices, Choice: choice, AllowCustom: true, Required: true}},
			Submit: func(ctx context.Context, values WorkflowValues) error {
				branches, err := m.repo.Branches(ctx)
				if err != nil {
					return err
				}
				for _, branch := range branches {
					if !branch.Remote && branch.Name == values["revision"] {
						return m.repo.CheckoutBranchWithOptions(ctx, branch.Name, checkoutOptions(command))
					}
				}
				return m.repo.CheckoutRevisionWithOptions(ctx, values["revision"], checkoutOptions(command))
			},
		}, nil
	})
}

func branchCheckoutRemote(m *Model, command WorkflowCommand) tea.Cmd {
	return loadBranchWorkflow(m, "remote branches", func(ctx context.Context) (WorkflowDialog, error) {
		choices, _, err := branchChoices(ctx, m.repo, true, true)
		if err != nil {
			return WorkflowDialog{}, err
		}
		remoteChoices := choices[:0]
		branches, err := m.repo.Branches(ctx)
		if err != nil {
			return WorkflowDialog{}, err
		}
		for _, branch := range branches {
			if branch.Remote {
				remoteChoices = append(remoteChoices, WorkflowChoice{Value: branch.Name, Label: branch.Name})
			}
		}
		if err := requireChoices(remoteChoices, "remote-tracking branches"); err != nil {
			return WorkflowDialog{}, err
		}
		return WorkflowDialog{
			Title: "Checkout remote ref", Operation: "checkout remote ref",
			Plan:   []string{"Checkout the exact selected remote-tracking ref with detached HEAD"},
			Fields: []WorkflowField{{Name: "revision", Label: "Remote ref", Kind: WorkflowSelect, Value: remoteChoices[0].Value, Choices: remoteChoices, Required: true}},
			Submit: func(ctx context.Context, values WorkflowValues) error {
				return m.repo.CheckoutRevisionWithOptions(ctx, values["revision"], checkoutOptions(command))
			},
		}, nil
	})
}

func branchCheckoutLocal(m *Model, command WorkflowCommand) tea.Cmd {
	return loadBranchWorkflow(m, "local branches", func(ctx context.Context) (WorkflowDialog, error) {
		choices, current, err := branchChoices(ctx, m.repo, false, true)
		if err != nil {
			return WorkflowDialog{}, err
		}
		if err := requireChoices(choices, "local branches"); err != nil {
			return WorkflowDialog{}, err
		}
		return WorkflowDialog{
			Title: "Checkout local branch (adapted)", Operation: "checkout local branch",
			Plan:   []string{"Adapted: choose an existing local branch; remote guessing is not performed"},
			Fields: []WorkflowField{{Name: "branch", Label: "Local branch", Kind: WorkflowSelect, Value: choiceDefault(choices, current), Choices: choices, Required: true}},
			Submit: func(ctx context.Context, values WorkflowValues) error {
				return m.repo.CheckoutBranchWithOptions(ctx, values["branch"], checkoutOptions(command))
			},
		}, nil
	})
}

func checkoutOptions(command WorkflowCommand) gitbackend.CheckoutOptions {
	for id, value := range command.Options {
		if !value.Enabled && value.Value == "" {
			continue
		}
		for _, binding := range keymap.Registry() {
			if binding.Command == id && binding.UpstreamCommand == "transient:magit-branch:--recurse-submodules" {
				return gitbackend.CheckoutOptions{RecurseSubmodules: true}
			}
		}
	}
	return gitbackend.CheckoutOptions{}
}

func branchOrphan(m *Model, _ WorkflowCommand) tea.Cmd {
	return loadBranchWorkflow(m, "orphan branch", func(context.Context) (WorkflowDialog, error) {
		return WorkflowDialog{
			Title: "Create orphan branch", Operation: "create orphan branch",
			Plan:   []string{"Create and checkout a new history-less branch"},
			Fields: []WorkflowField{{Name: "branch", Label: "New branch", Kind: WorkflowText, Required: true}},
			Submit: func(ctx context.Context, values WorkflowValues) error {
				return m.repo.CreateOrphanBranch(ctx, values["branch"])
			},
		}, nil
	})
}

func createBranchDialog(m *Model, checkout bool) WorkflowLoader {
	return func(ctx context.Context) (WorkflowDialog, error) {
		_, current, err := branchChoices(ctx, m.repo, false, true)
		if err != nil {
			return WorkflowDialog{}, err
		}
		start := "HEAD"
		if current != "" {
			start = current
		}
		title, operation, plan := "Create branch only", "create branch", "Create a local branch without changing HEAD"
		if checkout {
			title, operation, plan = "Create and checkout branch", "create and checkout branch", "Create a local branch and switch HEAD to it"
		}
		return WorkflowDialog{
			Title: title, Operation: operation, Plan: []string{plan},
			Fields: []WorkflowField{
				{Name: "branch", Label: "New branch", Kind: WorkflowText, Required: true},
				{Name: "start", Label: "Start point (revision)", Kind: WorkflowText, Value: start, Required: true},
			},
			Submit: func(ctx context.Context, values WorkflowValues) error {
				if checkout {
					return m.repo.CreateAndCheckoutBranch(ctx, values["branch"], values["start"])
				}
				return m.repo.CreateBranchOnly(ctx, values["branch"], values["start"])
			},
		}, nil
	}
}

func branchCreateAndCheckout(m *Model, _ WorkflowCommand) tea.Cmd {
	return loadBranchWorkflow(m, "branch creation", createBranchDialog(m, true))
}

func branchCreateOnly(m *Model, _ WorkflowCommand) tea.Cmd {
	return loadBranchWorkflow(m, "branch creation", createBranchDialog(m, false))
}

func branchWorktreeExisting(m *Model, _ WorkflowCommand) tea.Cmd {
	return loadBranchWorkflow(m, "worktree branch/revision", func(ctx context.Context) (WorkflowDialog, error) {
		_, current, err := branchChoices(ctx, m.repo, false, true)
		if err != nil {
			return WorkflowDialog{}, err
		}
		if current == "" {
			current = "HEAD"
		}
		return WorkflowDialog{
			Title: "Add worktree for branch/revision", Operation: "add worktree",
			Plan: []string{"Destination is validated by the worktree backend", "No force option is used"},
			Fields: []WorkflowField{
				{Name: "path", Label: "New worktree destination", Kind: WorkflowText, Required: true},
				{Name: "revision", Label: "Existing branch or revision", Kind: WorkflowText, Value: current, Required: true},
			},
			Submit: func(ctx context.Context, values WorkflowValues) error {
				return m.repo.AddWorktree(ctx, values["path"], values["revision"], gitbackend.WorktreeAddOptions{})
			},
		}, nil
	})
}

func branchWorktreeNew(m *Model, _ WorkflowCommand) tea.Cmd {
	return loadBranchWorkflow(m, "new branch worktree", func(ctx context.Context) (WorkflowDialog, error) {
		_, current, err := branchChoices(ctx, m.repo, false, true)
		if err != nil {
			return WorkflowDialog{}, err
		}
		if current == "" {
			current = "HEAD"
		}
		return WorkflowDialog{
			Title: "Add worktree with new branch", Operation: "add branch worktree",
			Plan: []string{"Validate and create a new local branch in a new worktree", "Destination is backend-validated; no force option is used"},
			Fields: []WorkflowField{
				{Name: "path", Label: "New worktree destination", Kind: WorkflowText, Required: true},
				{Name: "branch", Label: "New branch", Kind: WorkflowText, Required: true},
				{Name: "start", Label: "Start point (revision)", Kind: WorkflowText, Value: current, Required: true},
			},
			Submit: func(ctx context.Context, values WorkflowValues) error {
				return m.repo.AddWorktreeWithNewBranch(ctx, values["path"], values["branch"], values["start"])
			},
		}, nil
	})
}

func configuredLabel(name string, value gitbackend.ConfiguredValue) string {
	if !value.Set {
		return name + " (currently unset)"
	}
	return name + " (current: " + value.Value + ")"
}

func actionChoices(values ...string) []WorkflowChoice {
	choices := []WorkflowChoice{{Value: "keep", Label: "Keep current value"}, {Value: "unset", Label: "Unset"}}
	for _, value := range values {
		choices = append(choices, WorkflowChoice{Value: value, Label: "Set to " + value})
	}
	return choices
}

func branchConfigure(m *Model, _ WorkflowCommand) tea.Cmd {
	return loadBranchWorkflow(m, "branch configuration", func(ctx context.Context) (WorkflowDialog, error) {
		branches, current, err := branchChoices(ctx, m.repo, true, true)
		if err != nil {
			return WorkflowDialog{}, err
		}
		var locals, upstreams []WorkflowChoice
		for _, choice := range branches {
			upstreams = append(upstreams, choice)
			if !strings.Contains(choice.Label, "(remote-tracking)") {
				locals = append(locals, choice)
			}
		}
		if err := requireChoices(locals, "local branches"); err != nil {
			return WorkflowDialog{}, err
		}
		selected := choiceDefault(locals, current)
		remotes, err := m.repo.Remotes(ctx)
		if err != nil {
			return WorkflowDialog{}, err
		}
		remoteNames := make([]string, 0, len(remotes))
		for _, remote := range remotes {
			remoteNames = append(remoteNames, remote.Name)
		}
		upstreamActions := []WorkflowChoice{{Value: "keep", Label: "Keep current upstream"}, {Value: "unset", Label: "Unset upstream"}}
		for _, choice := range upstreams {
			upstreamActions = append(upstreamActions, WorkflowChoice{Value: choice.Value, Label: "Set to " + choice.Value})
		}
		rebaseModes := []string{"false", "true", "merges", "interactive"}
		autoSetupMergeModes := []string{"false", "true", "always", "simple", "inherit"}
		autoSetupRebaseModes := []string{"never", "local", "remote", "always"}
		d := WorkflowDialog{
			Title: "Configure branch and branch defaults", Operation: "configure branch",
			Plan: []string{"Select a branch and desired changes; review loads that branch's current values", "Each setting defaults to Keep; only explicit Set/Unset choices mutate configuration"},
			Fields: []WorkflowField{
				{Name: "branch", Label: "Local branch", Kind: WorkflowSelect, Value: selected, Choices: locals, Required: true},
				{Name: "description_action", Label: "Description action", Kind: WorkflowEnum, Value: "keep", Choices: actionChoices("set")},
				{Name: "description", Label: "Description value", Kind: WorkflowText},
				{Name: "upstream", Label: "Upstream action", Kind: WorkflowEnum, Value: "keep", Choices: upstreamActions},
				{Name: "rebase", Label: "Branch rebase action", Kind: WorkflowEnum, Value: "keep", Choices: actionChoices(rebaseModes...)},
				{Name: "push_remote", Label: "Branch pushRemote action", Kind: WorkflowEnum, Value: "keep", Choices: actionChoices(remoteNames...)},
				{Name: "pull_rebase", Label: "pull.rebase action", Kind: WorkflowEnum, Value: "keep", Choices: actionChoices(rebaseModes...)},
				{Name: "push_default", Label: "remote.pushDefault action", Kind: WorkflowEnum, Value: "keep", Choices: actionChoices(remoteNames...)},
				{Name: "auto_setup_merge", Label: "branch.autoSetupMerge action", Kind: WorkflowEnum, Value: "keep", Choices: actionChoices(autoSetupMergeModes...)},
				{Name: "auto_setup_rebase", Label: "branch.autoSetupRebase action", Kind: WorkflowEnum, Value: "keep", Choices: actionChoices(autoSetupRebaseModes...)},
			},
		}
		d.ReviewPreflight = func(ctx context.Context, values WorkflowValues) (WorkflowReview, error) {
			request := branchConfigRequest(values)
			reviewed, err := m.repo.ReviewBranchConfigUpdate(ctx, request)
			if err != nil {
				return WorkflowReview{}, err
			}
			return WorkflowReview{Plan: reviewed.Plan, Confirmation: "Apply exactly these reviewed configuration changes?", Data: reviewed}, nil
		}
		d.SubmitReview = func(ctx context.Context, _ WorkflowValues, review WorkflowReview) error {
			reviewed, ok := review.Data.(gitbackend.BranchConfigUpdate)
			if !ok {
				return errors.New("invalid branch configuration review")
			}
			return m.repo.ExecuteBranchConfigUpdate(ctx, reviewed)
		}
		return d, nil
	})
}

func branchConfigRequest(values WorkflowValues) gitbackend.BranchConfigUpdate {
	choice := func(value string) gitbackend.ConfigUpdate {
		switch value {
		case "keep":
			return gitbackend.ConfigUpdate{Action: gitbackend.ConfigKeep}
		case "unset":
			return gitbackend.ConfigUpdate{Action: gitbackend.ConfigUnset}
		default:
			return gitbackend.ConfigUpdate{Action: gitbackend.ConfigSet, Value: value}
		}
	}
	description := choice(values["description_action"])
	if description.Action == gitbackend.ConfigSet {
		description.Value = values["description"]
	}
	return gitbackend.BranchConfigUpdate{Branch: values["branch"], Description: description, Upstream: choice(values["upstream"]), Rebase: choice(values["rebase"]), PushRemote: choice(values["push_remote"]), PullRebase: choice(values["pull_rebase"]), RemotePushDefault: choice(values["push_default"]), AutoSetupMerge: choice(values["auto_setup_merge"]), AutoSetupRebase: choice(values["auto_setup_rebase"])}
}

func applyBranchConfiguration(ctx context.Context, repo *gitbackend.Repository, values WorkflowValues) error {
	branch := values["branch"]
	if err := applyBranchDescription(ctx, repo, branch, values["description_action"], values["description"]); err != nil {
		return err
	}
	steps := []func() error{
		func() error { return applyUpstream(ctx, repo, branch, values["upstream"]) },
		func() error {
			return applyRebase(ctx, values["rebase"], func(mode gitbackend.RebaseMode) error { return repo.SetBranchRebase(ctx, branch, mode) }, func() error { return repo.UnsetBranchRebase(ctx, branch) })
		},
		func() error {
			return applyRemote(values["push_remote"], func(remote string) error { return repo.SetBranchPushRemote(ctx, branch, remote) }, func() error { return repo.UnsetBranchPushRemote(ctx, branch) })
		},
		func() error {
			return applyRebase(ctx, values["pull_rebase"], func(mode gitbackend.RebaseMode) error { return repo.SetPullRebase(ctx, mode) }, func() error { return repo.UnsetPullRebase(ctx) })
		},
		func() error {
			return applyRemote(values["push_default"], func(remote string) error { return repo.SetRemotePushDefault(ctx, remote) }, func() error { return repo.UnsetRemotePushDefault(ctx) })
		},
	}
	for _, step := range steps {
		if err := step(); err != nil {
			return err
		}
	}
	return nil
}

func applyBranchDescription(ctx context.Context, repo *gitbackend.Repository, branch, action, description string) error {
	switch action {
	case "keep":
		return nil
	case "set":
		return repo.SetBranchDescription(ctx, branch, description)
	case "unset":
		return repo.UnsetBranchDescription(ctx, branch)
	default:
		return errors.New("invalid description action")
	}
}

func applyUpstream(ctx context.Context, repo *gitbackend.Repository, branch, action string) error {
	switch action {
	case "keep":
		return nil
	case "unset":
		return repo.UnsetBranchUpstream(ctx, branch)
	default:
		return repo.SetBranchUpstream(ctx, branch, action)
	}
}

func applyRebase(_ context.Context, action string, set func(gitbackend.RebaseMode) error, unset func() error) error {
	switch action {
	case "keep":
		return nil
	case "unset":
		return unset()
	case "false", "true", "merges", "interactive":
		return set(gitbackend.RebaseMode(action))
	default:
		return fmt.Errorf("invalid rebase action %q", action)
	}
}

func applyRemote(action string, set func(string) error, unset func() error) error {
	switch action {
	case "keep":
		return nil
	case "unset":
		return unset()
	default:
		return set(action)
	}
}

func branchRename(m *Model, _ WorkflowCommand) tea.Cmd {
	return loadBranchWorkflow(m, "branches to rename", func(ctx context.Context) (WorkflowDialog, error) {
		choices, current, err := branchChoices(ctx, m.repo, false, true)
		if err != nil {
			return WorkflowDialog{}, err
		}
		if err := requireChoices(choices, "local branches"); err != nil {
			return WorkflowDialog{}, err
		}
		return WorkflowDialog{
			Title: "Rename local branch", Operation: "rename local branch", Plan: []string{"Rename one local branch and its branch-local configuration"},
			Fields: []WorkflowField{
				{Name: "branch", Label: "Local branch", Kind: WorkflowSelect, Value: choiceDefault(choices, current), Choices: choices, Required: true},
				{Name: "new", Label: "New branch name", Kind: WorkflowText, Required: true},
			},
			Submit: func(ctx context.Context, values WorkflowValues) error {
				return m.repo.RenameBranch(ctx, values["branch"], values["new"])
			},
		}, nil
	})
}

func branchReset(m *Model, _ WorkflowCommand) tea.Cmd {
	return loadBranchWorkflow(m, "branches to reset", func(ctx context.Context) (WorkflowDialog, error) {
		choices, _, err := branchChoices(ctx, m.repo, false, false)
		if err != nil {
			return WorkflowDialog{}, err
		}
		if err := requireChoices(choices, "non-current local branches"); err != nil {
			return WorkflowDialog{}, err
		}
		return WorkflowDialog{
			Title: "Reset non-current local branch", Operation: "reset local branch",
			Plan: []string{"Move one non-current local branch ref; index and worktree are unchanged"},
			Fields: []WorkflowField{
				{Name: "branch", Label: "Non-current local branch", Kind: WorkflowSelect, Value: choices[0].Value, Choices: choices, Required: true},
				{Name: "revision", Label: "Target revision", Kind: WorkflowText, Value: "HEAD", Required: true},
			},
			Submit: func(ctx context.Context, values WorkflowValues) error {
				return m.repo.ResetBranch(ctx, values["branch"], values["revision"])
			},
		}, nil
	})
}

func branchDelete(m *Model, _ WorkflowCommand) tea.Cmd {
	return loadBranchWorkflow(m, "branches to delete", func(ctx context.Context) (WorkflowDialog, error) {
		choices, _, err := branchChoices(ctx, m.repo, false, false)
		if err != nil {
			return WorkflowDialog{}, err
		}
		if err := requireChoices(choices, "non-current local branches"); err != nil {
			return WorkflowDialog{}, err
		}
		return WorkflowDialog{
			Title: "Delete one non-current local branch", Operation: "delete local branch",
			Fields: []WorkflowField{{Name: "branch", Label: "Non-current local branch", Kind: WorkflowSelect, Value: choices[0].Value, Choices: choices, Required: true}},
			ReviewPreflight: func(ctx context.Context, values WorkflowValues) (WorkflowReview, error) {
				result, err := m.repo.LocalBranchDeletePreflight(ctx, values["branch"])
				if err != nil {
					return WorkflowReview{}, err
				}
				if result.Current || result.Confirmation == gitbackend.BranchDeleteSwitchCurrent {
					return WorkflowReview{}, fmt.Errorf("current branch %q cannot be deleted; switch branches first", result.Name)
				}
				state := "Branch is merged into " + result.MergeTarget
				if result.Unmerged {
					state = "Branch is not merged into " + result.MergeTarget
				}
				return WorkflowReview{
					Plan:         []string{"Delete local branch " + result.Name, "Reviewed OID " + result.OID, state},
					Confirmation: "Review the exact branch OID, then execute deletion",
					Data:         result,
				}, nil
			},
			SubmitReview: func(ctx context.Context, values WorkflowValues, review WorkflowReview) error {
				result, ok := review.Data.(gitbackend.LocalBranchDeleteResult)
				if !ok || result.Name == "" || result.Name != values["branch"] {
					return errors.New("invalid branch deletion review token")
				}
				_, err := m.repo.DeleteLocalBranchConfirmed(ctx, result.Name, result.Token)
				return err
			},
		}, nil
	})
}
